spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/bms?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 9090

jwt:
  secret:
    key: myjwtsec_without_hashing_adding-more-key-for-enhanced-security
    expiration: 3600000
